### ISSUE TITLE
[WheelVariants] Allow static metadata to override all provider plugin logic

### ISSUE THREAD

**Issue by zanieb** [wheelnext/pep_xxx_wheel_variants#42]
👋 

@DEKHTIARJonathan and I were talking about this at PyCon, so I'm posting a thread here.

Recently, the project has gone from user-installed provider plugins, to package-defined provider plugins. I think this is a great improvement for usability — most users will not want to reason about what providers plugins they need. However, this introduces concerns about attack surface. Now, even if you're only using binary distributions, you must invoke third-party code at install time in order to select an appropriate distribution. 

As a solution to this, I think the specification should allow for a manual list of variants to override all of the provider logic. If the user opts-in to providing this list, no provider plugins will be used.

The _mechanism_ for providing this list shouldn't be a part of the specification. This will be a user-experience consideration for tooling. For example, tools could support workflows where:

- You explicitly `pip install <plugin>` and those are detected at install-time and used to generate the static list
- You enumerate a list of plugins in your `pyproject.toml`, and those are installed and queried at install time instead
- You enumerate a list of plugins in some system-level file, and invoke a tool _once_ to write the static list to a file on boot — other tools can choose to read this file

As a nice property, something like the last case also addresses concerns about slowing down installation due to provider queries.

cc @charliermarsh @geofft @mgorny

**Comment by konstin** [comment]
> You enumerate a list of plugins in some system-level file, and invoke a tool once to write the static list to a file on boot — other tools can choose to read this file

For docker, it would be great if there was a system level location, so images come pre-made with e.g. the GPU they target.

---

I hope this isn't discussed in another thread already, but it matches the same goal of not running (arbitrary) code: It should also be allowed for the packaging tool to "vendor" variant providers: I suspect that the number of popular variant provider will be small (I expect something like a generic GPU/TPU plugin and one for processor SSE extensions), so by including them in the packaging tool, we can (a) avoid the security implications and (b) solve the performance and reliably issues of subprocess calls.

For pip and other tool written in Python, they could vendor the provider and call it directly, knowing that this provider doesn't need the isolation. For uv and other rust tool, they could use Rust implementations of the provider. This is similar to PEP 517, where some tool know their own build backend and can call it directly.

Implementation-wise, tools can only use vendored providers when they match the requested provider version, and should offer an opt-out to use the real provider.

**Comment by DEKHTIARJonathan** [comment]
I was quickly chatting with @zanieb on Discord. What about a file like `variant-env.lock` ?
A sort of `lockfile` concept - but capturing the "output of plugins".

You could execute `uv sync --variant-lock=variant-env.lock` - the resolution would still be dynamic (handled by `uv` or `variantlib`) but there would be no plugin being called.

This a **major** feature we need to account for ... for so many reasons.

**Comment by zanieb** [comment]
I'm not sure if the file itself needs to be part of the specification. It seems easier to just standardize what static metadata looks like during resolution and allow installers to figure out the user experience around the file name and format. I feel like a _future_ proposal could standardize a format, as we have for other things in the ecosystem. But anyway, I'm willing to talk about it. 

Why not just a flat text file listing variants? What other information is needed?

**Comment by DEKHTIARJonathan** [comment]
> I'm not sure if the file itself needs to be part of the specification. It seems easier to just standardize what static metadata looks like during resolution and allow installers to figure out the user experience around the file name and format. I feel like a future proposal could standardize a format, as we have for other things in the ecosystem. But anyway, I'm willing to talk about it.

My perspective is that we may end up with "optional PEPs" linked to the primary PEP.
Like extension of the "core proposal" - this would allow us to discuss in the core proposal the stuff **abssssollutely necessary** to make it work. And in "optional feature PEPs" - optional but nice to have standardized features/behaviors as extension of the standard
 
So that `variant-env.lock` would absolutely fall under "nice to have but optional" -making it a standard is really not necessary. Though if we can standardize it - it allows us to have an "installer independent" format - promotes compatibility and portability :)

**Comment by zanieb** [comment]
I think standardization of a lock file should be out of scope for the first wave, even as an optional PEP. In the sense that we need to understand how the specification is used before it's worth pursuing things like this.

Tell me more about your desired format anyway :D if it's trivial, I may be more into it.

**Comment by zanieb** [comment]
Why use an exploded table like that instead of just listing the strings?

I think all of those points are fine, tbh. The latter two are just arguments for static metadata, not necessarily a file format. On the first one, we _want_ people to come up with individual formats so we can learn what users actually need then standardize what's working. The specification should just explain support for static metadata, you're stepping into the domain of user experience by specifying where that metadata comes from. People will be able to do reproducible installs regardless of whether a file format is included in the specification.

**Comment by zanieb** [comment]
> however I do think if we don't include in the PEP a way to "freeze the plugin output to disk" we are going to have difficulties both on DPO and when people use variants to build containers.

I disagree with this premise. If the specification provides a clear way get the output of plugins, and a clear way to override plugins with static metadata, then I think the storage of said static metadata is not going to be a point of contention.

Why is a flat list of features not sufficient? Why do you want to dictate a more complex format and file name? I think you need answers to these questions or there's nothing worth standardizing. We'll have a much clearer picture of these user needs later. The specification should support the simplest possible way to override with static metadata, and more complex file format for that metadata can be introduced once there are use-cases for it.

**Comment by DEKHTIARJonathan** [comment]
Could you giving an example of what you have mind ? Something like I did above. So that it's easier for me to follow what you mean by `Why is a flat list of features not sufficient?`

**Comment by zanieb** [comment]
(matching the format used for wheel metadata)

**Comment by konstin** [comment]
Here's a first draft for the file format for static variants:

The target variant environment can be written to a file, and that file can be provided to the installer. The main intended workflow is that you run this on the target host and save the output. We provide a reference implementation in variantlib, but package managers can provide their own implementation, e.g. uv could create one from a lockfile. Of course, it's also possible to hand-write them for specific use case, but automatically generating them is less error prone.

One common use case is adding this file to a docker build, for example if the build host and the deployment host are different, or if the image comes with libraries pre-installed. For the first case, the CI machine may not have a GPU but a CPU with AVX-512, while the target machine has a CUDA-enabled GPU but no AVX-512. For the second case, an nvidia docker image may come with the CUDA libraries. Building in that container, we know we want CUDA-enabled packages, but we also don't need to install the CUDA libraries Python-side (to keep the image reasonably sized).

We're using a single file as it is the easiest to handle. This JSON file contains a single key `prepared-variants`. `prepared-variants` contains a list, where each entry is one provider. Each entry can contain three keys, `enable-if` (optional), `plugin-api` (mandatory) and `variants` (mandatory). `variants` contains a nested namespace -> features -> list of values mapping, in the same style as an entry in the `variants` key, which here is the merged output of all variant providers (one namespace per provider plugin).

```json
{
  "resolved-variants": [
    {
      "enable-if": "platform_machine == 'aarch64' or 'arm' in platform_machine",
      "plugin-api": "provider_variant_aarch64.plugin:AArch64Plugin",
      "variants": {
        "aarch64": {
          "bf16": ["on"],
          "fp16": ["on"],
          "i8mm": ["on"]
        }
      }
    },
    {
      "plugin-api": "gpu_provider",
      "variants": {
        "gpu": {
          "matmul": ["v2", "v1"]
        }
      }
    }
  ]
}
```

We can also use a TOML, JSON seems to transport better that this is not for user editing, and it's the same format we're already using. The name up for bikeshedding (I have no particular opinion), we can call this "resolved", "static", "prepared", etc. The key is distinct from the keys used in `variant[s].json` to avoid accidentally using one file as the other.

Upon installation, a user passes this file to their package manager. Instead of installing and running any provider plugins, the installer applies this file to evaluate variants and variant markers.

Only static providers are supported. I've elided the resolved `requires` here; it would be nice to ensure compatible versions, but it would be hard to correctly support something like the example below. (This would be easier if there was only a single requirement. In that case we could record the resolved version and check it against the requirement).

```json
{
  "requires": [
    "provider-variant-aarch64 >=0.0.1,<1; python_version >= '3.9'",
    "legacy-provider-variant-aarch64 >=0.0.1,<1; python_version < '3.9'"
  ]
}
```

An open question is whether passing a prepared variants file means that missing providers cause an error, whether they are used and only the resolved providers are skipped, or whether they are treated as empty/false.

I've been thinking about adding a `prepared-variants-marker` key, but we're already relying on users ensuring that the variants file matches the target host, so I couldn't find sufficient motivation to add it.

**Comment by konstin** [comment]
What I'm imagining is that we have one package A that use the variant requires `gpu>=2.2,<3`, B requires `gpu>=2.10,<3` and C requires `gpu>=3.10,<4`; Or `gpu>=2.2`, `gpu>=2.10` and `gpu2>=3.10`, if we want to avoid upper bounds. All of those packages use the `gpu` namespace. Since we're resolving to the highest versions, we're getting `gpu==2.20`, which handles A and B, and a separate package with separate properties for C.

Usually, I expect that there's more like package A to F that all work with the same provider version, though if we don't have any checks, we're prevent providers from ever making breaking changes and errors due to version mismatches are silent. OTOH it's reasonable to direct some of the responsibility to the user, since they are already asserting that the static file they are passing correctly represent the host the code runs on.

**Comment by DEKHTIARJonathan** [comment]
I'm proceeding to add in the specs the structure that @konstin except that if everybody is okay I would prefer to use TOML instead of JSON.

- Easier to read
- Easier to write by hand

```toml
[metadata]
created-timestamp = "2025-08-20T05:06:14+00:00"  # RFC 3339 and ISO 8601
created-by = "tool-that-created-the-file"
version = "0.0.1"

[[resolved-variants]]
enable-if = "platform_machine == 'aarch64' or 'arm' in platform_machine"
plugin-api = "provider_variant_aarch64.plugin:AArch64Plugin"

[resolved-variants.variants.aarch64]
bf16 = [ "on" ]
fp16 = [ "on" ]
i8mm = [ "on" ]

[[resolved-variants]]
plugin-api = "gpu_provider"

[resolved-variants.variants.gpu]
matmul = [ "v2", "v1" ]
```

For the `metadata` entry - only the `version` field in mandatory. Anything else is accepted.

Whenever I or @mgorny have a minute we'll add this to `variantlib` :D 

Works for everybody as a "design for the PEP" ?

**Comment by DEKHTIARJonathan** [comment]
Let's start iterating from what @konstin pushed forward. 

- I would prefer TOML over JSON. I suspect some people will write these files by hand - I do think this is important. People who are extremely "remote code execution averse" will most likely write these by hand.
    - Easier to read
    - Easier to write by hand

So what you proposed @konstin in TOML

```toml
[metadata]
created-timestamp = "2025-08-20T05:06:14+00:00"  # RFC 3339 and ISO 8601
created-by = "tool-that-created-the-file"
version = "0.0.1"

[[resolved-variants]]
enable-if = "platform_machine == 'aarch64' or 'arm' in platform_machine"
plugin-api = "provider_variant_aarch64.plugin:AArch64Plugin"

[resolved-variants.variants.aarch64]
bf16 = [ "on" ]
fp16 = [ "on" ]
i8mm = [ "on" ]

[[resolved-variants]]
plugin-api = "gpu_provider"

[resolved-variants.variants.gpu]
matmul = [ "v2", "v1" ]
```

## A few comments

1. Do we really need these `enable-if` and `plugin-api`. The plugin is frozen it would cost milliseconds to run no matter what if variants are enabled. This really makes the file more difficult to write by hand. I would prefer not. The plugin is already "statically executed" if you need it you have the information - I don't see the point to add these.

3. @konstin was hinting on it. I think there's a good chance for different packages to use different version of the same plugin we need to support that better.

## Here is what I would propose

1. Let's add file-level metadata. It's always useful to have at least for a "version string". Only the "version" field is required. Anything else is purely for humans.

2. Let's remove entirely `enable-if` and `plugin-api`

3. Freeze per package or `__all__` (if a package is explicitly named, takes priority over `__all__`)

```toml
[metadata]
version = "1.0.0"
created-by = "tool or person"
created-date = "whatever"

[[__all__]]

[__all__.aarch64.metadata]
package-name = "aarch64-provider-plugin"
version = "1.2.3"

[package_name.aarch64.variants]
bf16 = [ "on" ]
fp16 = [ "on" ]
fp8 = [ "on" ]
i8mm = [ "on" ]

[__all__.gpu.metadata]
package-name = "gpu-provider-plugin"
version = "4.5.6"

[__all__.gpu.variants]
matmul = [ "v3", "v2", "v1" ]

[[package_name]]

[package_name.aarch64.metadata]
package-name = "aarch64-provider-plugin"
version = "1.2.0"
[package_name.aarch64.variants]
bf16 = [ "on" ]
fp16 = [ "on" ]
i8mm = [ "on" ]

[package_name.gpu.metadata]
package-name = "gpu-provider-plugin"
version = "4.5.0"
[package_name.gpu.variants]
matmul = [ "v2", "v1" ]
```

In practice it's very very close to what @konstin was proposing

**Comment by DEKHTIARJonathan** [comment]
@mgorny the reason why I'm tempted to make it "optional" is that this could be a very nice mechanism to work hand-in-hand with `private` namespaces where no plugin actually exist. It's purely text-based

**Comment by DEKHTIARJonathan** [comment]
@rgommers I agree with everything you said. That being said - I would prefer starting with TOML and switch to JSON if the community insists.

@konstin & @mgorny : happy with my proposal above ? Any remark before "we close this for now" ?

**Comment by DEKHTIARJonathan** [comment]
I need something to include in the PEP - I think it's a strong argument in defense of remote code exec.

If we were to proceed with the full format you're proposing - it's conceptually very close to "variant environment lock file"

I would probably call it that `variant.lock` and proceed in TOML

### `variant.lock`

```toml
[metadata]
created-timestamp = "2025-08-20T05:06:14+00:00"  # RFC 3339 and ISO 8601
created-by = "tool-that-created-the-file"
version = "0.0.1"

[[package_name]]
enable-if = "platform_machine == 'aarch64' or 'arm' in platform_machine"
plugin-api = "provider_variant_aarch64.plugin:AArch64Plugin"

[package_name.variants.aarch64]
bf16 = [ "on" ]
fp16 = [ "on" ]
i8mm = [ "on" ]

[[package_name]]
plugin-api = "gpu_provider"

[package_name.variants.gpu]
matmul = [ "v2", "v1" ]
```

I'm really not convinced we should not make this file intended to be "written by hand". 
There's a serious use-case to consider that revolves around "building containers" where the target machine might not really exist to "variant lock" but rather be hypothetical in between / common denominator.
